draft: feat: Detect & Destroy media spam
danparizher/Pax-Academia pull request #280
Opened 2024-01-04 00:37 UTC by GabeMillikan

WIP

2024-01-05 11:15 UTC, sebastiaan-daniels approved these changes
LGTM, dont forget to label your PR.

2024-01-05 15:10 UTC, danparizher requested changes
Thank you for your work on this! Just a few suggestions, let me know what you think.

2024-01-05 15:10 UTC, danparizher commented on cogs/detect_media_spam.py
> +        return media_messages
```suggestion
    def pop_media_messages(self) -> list[discord.Message]:
        return [
            self.history.pop(i).message
            for i in range(len(self.history) - 1, -1, -1)
            if self.history[i].mostly_media
        ]
```

2024-01-05 15:10 UTC, danparizher commented on cogs/detect_media_spam.py
> +                            f"{channel_monitor.media_pixels}",
```suggestion
                            str(channel_monitor.media_pixels),
```

2024-01-05 15:10 UTC, danparizher commented on cogs/detect_media_spam.py
> +                            f"{channel_monitor.textual_pixels}",
```suggestion
                            str(channel_monitor.textual_pixels),
```

2024-01-06 22:14 UTC, GabeMillikan commented
> Thank you for your work on this! Just a few suggestions, let me know what you think.

👍Applied those suggestions

2024-01-06 22:16 UTC, danparizher approved these changes

2024-01-23 10:28 UTC, ceSchueler requested changes
Remove the functionality of deleting the messages `async def delete_media_messages ...` and I'll approve it in woseek's stead as then it would _really_ just be the monitoring of the percentage.
For the actual deletion part (added with another PR at a later date), I would leave the approval to woseek himself then.

2024-01-26 04:38 UTC, GabeMillikan commented
@ceSchueler 
> Remove the functionality of deleting the messages `async def delete_media_messages ...` and I'll approve it in woseek's stead as then it would _really_ just be the monitoring of the percentage. For the actual deletion part (added with another PR at a later date), I would leave the approval to woseek himself then.

Sure 👍, I've removed that function from this PR entirely. (see: 8c1c433)

2024-01-27 00:30 UTC, ceSchueler approved these changes

2024-01-27 00:35 UTC, merged